"""Added data to the tables

Revision ID: 3518bb5f0fa1
Revises: 0985a3480d56
Create Date: 2024-01-10 10:25:40.867701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3518bb5f0fa1'
down_revision = '0985a3480d56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('marks', sa.Integer(), nullable=True))
    op.drop_column('marks', 'mark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('mark', sa.INTEGER(), nullable=True))
    op.drop_column('marks', 'marks')
    # ### end Alembic commands ###
