"""Added the database and its tables

Revision ID: 42e8206d4e9e
Revises: 649b16ac0bba
Create Date: 2024-01-10 11:13:39.947950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e8206d4e9e'
down_revision = '649b16ac0bba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
