"""Added data to the tables

Revision ID: 649b16ac0bba
Revises: 3518bb5f0fa1
Create Date: 2024-01-10 10:26:16.707298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649b16ac0bba'
down_revision = '3518bb5f0fa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('mark', sa.Integer(), nullable=True))
    op.drop_column('marks', 'marks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('marks', sa.INTEGER(), nullable=True))
    op.drop_column('marks', 'mark')
    # ### end Alembic commands ###
